spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  cloud:
      consul:
        enabled: false
  datasource:
      name: mysql_dataSource
#      url: jdbc:mysql://172.20.28.31:3306/kpi
      url: jdbc:mysql://127.0.0.1:3306/kokoharry
      username: root
      password: 423111lyb
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  freemarker:
      suffix: .ftl  #后缀名
      cache: false #缓存配置
      template-loader-path: classpath:/templates/ #模板加载路径 按需配置
server:
  port: ${port0:80}

mybatis:
  mapper-locations: classpath:mapping/**/*.xml

